//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS4930_Mini_Project_1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using CIS4930_Mini_Project_1.Models;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TODOLIST> TODOLISTs { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<USERSSAFE> USERSSAFEs { get; set; }
        public virtual DbSet<SHOWTODO> SHOWTODOS { get; set; }
        public virtual DbSet<SHOWTODOSSAFE> SHOWTODOSSAFEs { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
