//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS4930GCP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int index { get; set; }
        public string id { get; set; }
        public string username { get; set; }
        public string name { get; set; }
        public string hashedkey { get; set; }
    }
}
